# 1. 13

## 1.1. 问题

### 1.1.1. 问题1

1.函数执行时，如果由于 panic 导致了异常，则延迟函数不会执行。这一说法是否正确？
A. true
B. false

### 1.1.2. 问题2

下面代码输出什么？

```go
func main() {
    a := [3]int{0, 1, 2}
    s := a[1:2]

    s[0] = 11
    s = append(s, 12)
    s = append(s, 13)
    s[0] = 21

    fmt.Println(a)
    fmt.Println(s)
}
```

## 1.2. 答案

### 1.2.1. 答案1

参考答案及解析：B。
由 panic 引发异常以后，程序停止执行，然后调用延迟函数（defer），就像程序正常退出一样。

### 1.2.2. 答案2

```
[0 11 12]
[21 12 13]
```
